default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vitalii
  password: vitapass

development:
  <<: *default
  database: event-planning-API_development

test:
  <<: *default
  database: event-planning-API_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: event-planning-API_production
