default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: event-planning-API_development

test:
  <<: *default
  database: event-planning-API_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: event-planning-API_production
